apiVersion: backstage.io/v1alpha1
kind: Api
metadata:
  name: PetStoreAPI
  title: PetStore API
spec:
  specUrl: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/petstore-simple.json
  owner: JPL Backstage Team
  type: external
  description: Petstore APIs
  tags: pet
